/**
 * This code was generated by Builder.io.
 */
import { useState } from "react";
import Header from "./Header";
import Hero from "./Hero";


const FirstScreen = () => {
  return (
    <div>
        <Header />
        <Hero />
    </div>
  );
};

export default FirstScreen;
