/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header = () => {
  return (
<header className="flex w-full flex-row justify-center items-center text-emerald-700">
  <div className=" w-1/5 text-2xl ">
    LOGO
  </div>
  <nav className="w-3/5 flex flex-row items-center justify-center text-xl">
    <div className="w-[100px] font-bold">Home</div>
    <div className="w-[100px]">Services</div>
    <div className="w-[100px]">Contact Us</div>
  </nav>
  <div className="w-1/5 text-center text-lg">
    <button 
    style={{borderBottomRightRadius:'30px'}} 
    className="w-[100px] text-lg  border border-emerald-700 border-solid py-2">
      Sign In
    </button>
  </div>
</header>
  );
};

export default Header;
