/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero = () => {
  return (
    <section className="self-stretch mt-14 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">

        <div className="flex flex-col w-[70%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col mt-11 text-2xl leading-9 text-black max-md:mt-10 max-md:max-w-full pr-[30px]">
            <h1 className="text-4xl font-bold text-emerald-700 max-md:max-w-full">
              Empowering NGOs and Companies to Transform Child Health Data
            </h1>
            <p className="mt-11 font-medium max-md:mt-10 max-md:max-w-full">
              Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis.
              Scelerisque dolor fermentum pellentesque tincidunt gravida
              praesent sed.
            </p>
            <p className="mt-9 max-md:mr-2 max-md:max-w-full">
              Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis.
              Scelerisque dolor fermentum pellentesque dolor fermentum
              pellentesque tincidunt gravida praesent sed.
            </p>
            <button style={{ borderBottomRightRadius: '30px' }} className="justify-center self-start px-6 py-4 mt-9 text-lg leading-7 text-white bg-emerald-700 rounded-none max-md:px-5">
              Get Started
            </button>
          </div>
        </div>

        <div className="flex flex-col ml-5 w-7/12 max-md:ml-0 max-md:w-full">
          <div className="grow max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">

              <div className="flex flex-col w-[95%] max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/7dc7ff8e8701674d67bd413a393763249320904b83d4f8cee61a49661c02860a?apiKey=27e3725db8b34053b390a33ddc94eaed&"
                  alt=""

                  className="z-10 w-full max-md:max-w-full"
                />
              </div>

            </div>
          </div>
        </div>

      </div>
      
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/48c7f0ca0d33b73a37b316526c26614c6340d12831573739809d5b261b3803d4?apiKey=27e3725db8b34053b390a33ddc94eaed&"
        alt=""
        style={{ position: 'absolute', right: '0px', top: '0px', width: '500px' }}
      />
    </section>
  );
};

export default Hero;
