/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ServiceSlide = ({ imageSrc, title, description }) => (
  <div className="flex overflow-hidden relative flex-col gap-5 justify-between pt-12 pr-5 pb-4 pl-2.5 w-full fill-[url(<path-to-image>)_lightgray_0px_0.25px_/_100%_118.25%_no-repeat] min-h-[600px] max-md:flex-wrap max-md:max-w-full">
    <img
      loading="lazy"
      src={imageSrc}
      alt=""
      className="object-cover absolute inset-0 size-full"
    />
    <div className="flex relative gap-0 max-md:flex-wrap">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b65cb13c83282ae957700520378b85d394c3f737c187f3614be9156ba5182d04?apiKey=27e3725db8b34053b390a33ddc94eaed&"
        alt=""
        className="shrink-0 my-auto aspect-square w-[60px]"
      />
      <div className="flex flex-col grow shrink-0 basis-0 w-fit max-md:max-w-full">
        <h2 className="text-4xl font-bold text-neutral-300 max-md:max-w-full">
          {title}
        </h2>
        <p className="mt-5 text-2xl leading-9 text-white max-md:max-w-full">
          {description}
        </p>
        <div className="flex gap-2.5 self-end mt-80 max-md:mt-10">
          {[...Array(6)].map((_, index) => (
            <div
              key={index}
              className={`shrink-0 w-6 h-6 ${
                index === 0 ? "bg-emerald-700" : "bg-white"
              } rounded-full`}
            />
          ))}
        </div>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/498a10b7c69a937ec1a4da444190b17cb2220e0ae64e75fb3fe54d1bc6b0efc9?apiKey=27e3725db8b34053b390a33ddc94eaed&"
        alt=""
        className="shrink-0 my-auto aspect-square w-[60px]"
      />
    </div>
  </div>
);

const ServiceSlider = () => {
  const services = [
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/af88bf3bb70361b071ef89be36f11441033d38379b367cea2d489301048e1e3f?apiKey=27e3725db8b34053b390a33ddc94eaed&",
      title: "Zakah and Sadaqah services",
      description:
        "Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis. Scelerisque dolor fermentum pellentesque dolor fermentum pellentesque tincidunt gravida praesent sed.",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/931823e0415bf4630117da0c296d1ad5bc4f15e52827de9cb4c412f60153a891?apiKey=27e3725db8b34053b390a33ddc94eaed&",
      title: "Orphan and prisoners welfare",
      description:
        "Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis. Scelerisque dolor fermentum pellentesque dolor fermentum pellentesque tincidunt gravida praesent sed.",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ca046a62429c37a5d23bb1958ac42ad182f0ee37fd489e5948612e413e1fc012?apiKey=27e3725db8b34053b390a33ddc94eaed&",
      title: "Water Aid",
      description:
        "Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis. Scelerisque dolor fermentum pellentesque dolor fermentum pellentesque tincidunt gravida praesent sed.",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ca046a62429c37a5d23bb1958ac42ad182f0ee37fd489e5948612e413e1fc012?apiKey=27e3725db8b34053b390a33ddc94eaed&",
      title: "Building Islamic schools and mosques",
      description:
        "Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis. Scelerisque dolor fermentum pellentesque dolor fermentum pellentesque tincidunt gravida praesent sed.",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ca046a62429c37a5d23bb1958ac42ad182f0ee37fd489e5948612e413e1fc012?apiKey=27e3725db8b34053b390a33ddc94eaed&",
      title: "Da'awah committee",
      description:
        "Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis. Scelerisque dolor fermentum pellentesque dolor fermentum pellentesque tincidunt gravida praesent sed.",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ca046a62429c37a5d23bb1958ac42ad182f0ee37fd489e5948612e413e1fc012?apiKey=27e3725db8b34053b390a33ddc94eaed&",
      title: "Emergency & Health care services",
      description:
        "Lorem ipsum dolor sit amet consectetur. Et vitae sapien odio dis. Scelerisque dolor fermentum pellentesque dolor fermentum pellentesque tincidunt gravida praesent sed.",
    },
  ];

  return (
    <section className="flex overflow-x-auto z-10 gap-5 justify-between self-stretch mt-0 max-md:flex-wrap max-md:max-w-full">
      {services.map((service, index) => (
        <div key={index} className="flex flex-col pb-5 max-md:max-w-full">
          <ServiceSlide {...service} />
        </div>
      ))}
    </section>
  );
};

export default ServiceSlider;
