/**
 * This code was generated by Builder.io.
 */
import React from "react";

const StatisticCard = ({ value, label }) => (
  <div className="text-2xl leading-9 text-black text-opacity-70 max-md:mt-10">
    <span className="text-6xl font-medium text-emerald-700">{value}</span>
    <br />
    <span className="text-black">{label}</span>
  </div>
);

export default StatisticCard;
