/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StatisticCard from "./StatisticCard";

const StatisticsSection = () => {
  const statistics = [
    { value: "5,000+", label: "Children Monitored" },
    { value: "98%", label: "Form Submission rate" },
    { value: "200+", label: "AI Reports Generated" },
    { value: "30+", label: "Countries Engaged" },
  ];

  return (
    <section className="mx-7 mt-10 max-md:mr-2.5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        {statistics.map((stat, index) => (
          <div
            key={index}
            className={`flex flex-col ${
              index === 0 ? "w-[23%]" : "ml-5 w-[25.67%]"
            } max-md:ml-0 max-md:w-full`}
          >
            <StatisticCard {...stat} />
          </div>
        ))}
      </div>
    </section>
  );
};

export default StatisticsSection;
