/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TestimonialCard = ({ quote, name, title, avatarSrc }) => (
  <div className="flex flex-col grow px-6 py-11 w-full bg-white rounded-sm border border-emerald-700 border-solid shadow-sm text-zinc-700 max-md:px-5 max-md:mt-10 max-md:max-w-full">
    <div className="text-7xl font-semibold text-emerald-700 leading-[80px] max-md:text-4xl">
      "
    </div>
    <h3 className="mt-11 text-2xl leading-9 text-stone-900 max-md:mt-10">
      {quote}
    </h3>
    <p className="mt-4 text-base leading-6">
      Lorem Ipsum is simply dummy text Lorem Ipsum is simply dummy text Lorem
      Ipsum is simply dummy text Lorem Ipsum is simply dummy text Lorem Ipsum is
    </p>
    <div className="flex gap-3.5 mt-16 leading-[150%] max-md:mt-10">
      <img
        loading="lazy"
        src={avatarSrc}
        alt={name}
        className="shrink-0 rounded-full aspect-square w-[78px]"
      />
      <div className="flex flex-col grow shrink-0 self-start mt-3 basis-0 w-fit">
        <div className="text-2xl">{name}</div>
        <div className="text-base">{title}</div>
      </div>
    </div>
  </div>
);

export default TestimonialCard;
