# Generated by Django 5.0.7 on 2024-07-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='data_collector_name',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='data_collector_phone_number',
        ),
    ]
