# Generated by Django 5.0.7 on 2024-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_childfollowup_muac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinformation',
            name='vaccination_status',
            field=models.TextField(),
        ),
    ]
