# Generated by Django 5.0.7 on 2024-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_childinformation_vaccination_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childinformation',
            name='health_card_verification',
        ),
        migrations.AddField(
            model_name='childinformation',
            name='health_card_verified',
            field=models.BooleanField(default=False),
        ),
    ]
