# Generated by Django 5.0.7 on 2024-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0002_alter_antenatalfollowup_muac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalfollowup',
            name='weight_gain',
            field=models.FloatField(),
        ),
    ]
