# Generated by Django 5.0.7 on 2024-07-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0003_alter_antenatalfollowup_weight_gain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antenatalfollowup',
            old_name='weight_gain',
            new_name='weight',
        ),
    ]
