export const labelClass = 'block text-sm font-medium text-gray-700'
export const inputClass = 'mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm'
export const checkinputClass = 'mt-2 p-2 block w-1/4 border border-gray-300 rounded-md shadow-sm focus:ring-0 focus:border-emerald-0 sm:text-sm'
export const submitclassName='mt-4 w-full bg-emerald-500 text-white p-2 rounded-md shadow-sm hover:bg-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-opacity-50 cursor-pointer'
export const textareaclassName='mt-1 p-2 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm'
